# This is the basic congif file that has to be populated with the specific paths to the datasets
path: .../

train: images/train

val: images/val

test: images/val

kpt_shape: [17, 3]

flip_idx: [1, 0, 2, 3, 4, 8, 9, 10, 5, 6, 7, 14, 15, 16, 11, 12, 13]

names:
  0: quadruped